### ISSUE TITLE
Add steamid32 to profile and make both (64 and 32) better copyable

### ISSUE THREAD

**Issue by ibot3** [matbyte-com/vyhub-web#38]

**Comment by Lordisch** [comment]
[Added SteamID32](https://github.com/matbyte-com/vyhub-web/commit/e46d5fabb2eac833b59bca8d56ad3f878509ee95)
[Better copyable](https://github.com/matbyte-com/vyhub-web/commit/e46d5fabb2eac833b59bca8d56ad3f878509ee95)
